name: Lint
on: [push, pull_request]
jobs:
    build:
        name: App configuration
        runs-on: ubuntu-latest
        steps:
            - name: ⤵️ Check out code from GitHub
              uses: actions/checkout@v4
            - name: 🚀 Run Home Assistant App Lint
              uses: frenck/action-app-linter@v2
              with:
                  path: "./diyhue"
